### ISSUE TITLE
Add reasoning in h_closures_threads for crossbeam

### ISSUE THREAD

**Issue by Jerakin** [CleanCut/ultimate_rust_crash_course#15]
I am leaning rust and taking your course (on skillshare if you are currious)) and everything have been super clear so far, the only thing I haven't liked is that you say

```rust
    // Time for some fun with threads and channels!  Though there is a primitive type of channel
    // in the std::sync::mpsc module, I recommend always using channels from the crossbeam crate,
    // which is what we will use here.
```

Without giving a reason why you prefer the crate over the std library. Do you have an article (or know of one) which goes into why crossbeam is better than the std library, or maybe the reason is so simple you can summerize it in a sentence or two?

The video chapters/lessons never mentions channels either, so as I don't know what `channel::` _is_ I have a hard time even understanding it and its user cases.

**Comment by Jerakin** [comment]
I found your comment on the lesson. Closing this.
> In a nutshell, the folks who made std::sync::mpsc put it in the standard library too soon, and then couldn't change it because of Rust's commitment to long-term non-breaking-ness of the standard library. So they made the crossbeam crate and kept on improving channels there. This also serves as the cautionary tale of why-we-don't-add-things-to-the-standard-library-until-they're-super-stable.

**Comment by CleanCut** [comment]
👍🏻 😉
