### ISSUE TITLE
exercise e_ownership_references add

### ISSUE THREAD

**Issue by KonradHoeffner** [CleanCut/ultimate_rust_crash_course#27]
I just wrote `fn add(a: &i32, b: &i32) -> i32 {a+b}` which works correctly, is that intended? There seems to be no manual dereferencing needed, has that changed since your created the exercises?
Or is the correct answer `*a+*b` with explicit dereferencing?

```
  // Challenge: Write a function "add" that takes *references* to two integer arguments,
    // dereferences them and adds them together, and returns the result.
    //
    println!("1 + 2 = {}, even via references", add(&1, &2));   
```

**Comment by CleanCut** [comment]
Yes, that changed. For convenience Rust can now do math between any mix of integers and their references. In the course refresh I'm working on I'm changing the types to something where you will get an error if you don't dereference.
