### ISSUE TITLE
Unknown variable reference in Exercise A: answers.md

### ISSUE THREAD

**Issue by sm1215** [CleanCut/ultimate_rust_crash_course#9]
Hey there, 
I'm working through the first exercise and reviewing the answers. I see there's a reference to a [`loaded`](https://github.com/CleanCut/ultimate_rust_crash_course/blame/master/exercise/a_variables/ANSWERS.md#L77) variable, but I don't see this mentioned in the readme instructions. Perhaps this was meant to be `ready`? Small nitpick but thought you might like to know! If not, no worries. Have a good one 👋

**Comment by CleanCut** [comment]
@sm1215 Nice catch, thanks!  I went through the answers document and refreshed the whole thing in addition to fixing the problem you mentioned in https://github.com/CleanCut/ultimate_rust_crash_course/commit/a6785f3e7bc525f31150fa920be90041bc08d0d4
